version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: cashflow_pg
    environment:
      POSTGRES_USER: cashflow
      POSTGRES_PASSWORD: cashflow
      POSTGRES_DB: cashflow
    ports:
      - "5432:5432"
    volumes:
      - cashflow_pg_data:/var/lib/postgresql/data
volumes:
  cashflow_pg_data:
