spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cashflow
    username: cashflow
    password: cashflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

ai:
  provider: openai
  openai:
    apiKey: ${OPENAI_API_KEY}
    model: "gpt-4.1-mini"

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    org.springframework.web: INFO
